### ISSUE TITLE
Add usage docs or readme section

### ISSUE THREAD

**Issue by kolayne** [physarumAdv/Physarum_webGL#19]
There should be something explaining how I can start your project. The first issue I had was I needed to install dependencies before running the server, but I didn't find the dependencies list anywhere. Fortunately, I had to install just one library, but there may be more of them in future, so it's not nice. The second problem is, installing the dependencies is not enough! Looks like I have to do something else to use the project because when I start it and visit the webpage from my browser, I get the not found error on the `http://localhost:8080/lib/saves/names.json` URL. In fact, I don't even want to have saves, I want to just view my particles live (probably it has something to do with #15)

By the way, why are saves stored inside of lib?! It might be worth opening a separate issue

**Comment by pavtiger** [comment]
So, installing dependencies is fixed now, will fix everything else now

**Comment by kolayne** [comment]
Now, this is not fixed unless it's in master. And the master's README still contains no usage instructions

**Comment by kolayne** [comment]
Now this _is_ fixed (by #21)
